//This class is generated by convert_string.py
//DO NOT modify this class manually

import Foundation

class Text {

    static let CANCEL = NSLocalizedString("CANCEL", comment:"")

    static let ERR_DENIED_SAVE = NSLocalizedString("ERR_DENIED_SAVE", comment:"")

    static let ERR_FAIL_LOAD = NSLocalizedString("ERR_FAIL_LOAD", comment:"")

    static let ERR_FAIL_OPEN_INSTAGRAM = NSLocalizedString("ERR_FAIL_OPEN_INSTAGRAM", comment:"")

    static let ERR_FAIL_SAVE = NSLocalizedString("ERR_FAIL_SAVE", comment:"")

    static let LOG_IN = NSLocalizedString("LOG_IN", comment:"")

    static let LOG_OUT = NSLocalizedString("LOG_OUT", comment:"")

    static let MSG_BACK_TO_LIST = NSLocalizedString("MSG_BACK_TO_LIST", comment:"")

    static let MSG_FIRST_SAVED = NSLocalizedString("MSG_FIRST_SAVED", comment:"")

    static let MSG_OPEN_PHOTOS = NSLocalizedString("MSG_OPEN_PHOTOS", comment:"")

    static let MSG_OPEN_WITH_INSTAGRAM = NSLocalizedString("MSG_OPEN_WITH_INSTAGRAM", comment:"")

    static let MSG_SHOW_INSTRUCTION = NSLocalizedString("MSG_SHOW_INSTRUCTION", comment:"")

    static let OK = NSLocalizedString("OK", comment:"")

    static let SEARCH_BOX_PLACEHOLDER = NSLocalizedString("SEARCH_BOX_PLACEHOLDER", comment:"")

    static let SEARCH_DEFAULT_KEYWORD = NSLocalizedString("SEARCH_DEFAULT_KEYWORD", comment:"")

}